name: MountainDewritoes
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.MountainDewritoes.MountainDewritoes
depend:
- CustomItemRecipes
- GrandioseAPI
softdepend:
- ExtraHardMode
- Healthbar
- Multiverse-Core
- SimpleClans
- GriefPrevention
- PurpleIRC
- Chester
- EssentialsChat
- HolographicDisplays
- BetterTPA
- MCJukebox
- WorldBorder
- NoMyStuff
#Currently needed until we nuke crackshot
loadbefore:
- AbsorptionShields
commands:
  nick:
    aliases: [color, name, nickname, changecolor]
  warp: {}
  mdebug: {}
  restart:
    aliases: [stop]
  schedulerestart: {}
  clearchat:
    aliases: [chatclear]
  tip:
    aliases: [getatip, betafish, beta, tips]
  voice:
    aliases: [v]
  shrug: {}
  lejail: {}
  reset: {}
  md: {}
  watchwinreward: {}
  view:
    aliases: [viewdistance, distance, vd, renderdistance, render]
    usage: "/view [chunk radius] - Modifies view distance. Radius must be between 3-16. Also note that despite what you set here, you will still need to modify the render distance in Options > Video settings to see further."