name: MountainDewritoes
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.MountainDewritoes.MountainDewritoes
softdepend:
- ExtraHardMode
- Healthbar
- Multiverse-Core
- SimpleClans
- ActionAnnouncer
- GriefPrevention
- PurpleIRC
- Chester
- EssentialsChat
- HolographicDisplays
commands:
  nick:
    aliases: [color]