name: MountainDewritoes
version: ${git.commit.id.describe-short}
website: https://robomwm.com
author: RoboMWM
main: me.robomwm.MountainDewritoes.MountainDewritoes
api-version: 1.13
depend:
- CustomItemRecipes
- GrandioseAPI
softdepend:
- ExtraHardMode
- Healthbar
- Multiverse-Core
- SimpleClans
- GriefPrevention
- PurpleIRC
- Chester
- EssentialsChat
- HolographicDisplays
- BetterTPA
- WorldBorder
- NoMyStuff
- ServerListPlus
- PrettySimpleShop
- ProtocolLib
#Currently needed until we nuke crackshot
loadbefore:
- AbsorptionShields
#Wenu2lazy2command.yml
#- icJukeBox
commands:
  nick:
    aliases: [color, name, nickname, changecolor, namecolor, nickcolor]
  warp: {}
  mdebug: {}
  restart:
    aliases: [stop]
  restartnow: {}
  update: {}
  clearchat:
    aliases: [chatclear]
  tip:
    aliases: [getatip, betafish, beta, tips]
  voice:
    aliases: [v, voiceline, callout, voicelines, voices]
  start:
      aliases: [menu, book, bookmenu, menubook, gui, ui, main, mainmenu, help, info, page, pda]
  music:
      aliases: [song, sound]
  shrug: {}
  lejail: {}
  reset: {}
  md: {}
  watchwinreward: {}
  newlog: {}
  deletelog: {}
  info:
    aliases: [stat, stats, about, ip]
  settings:
    aliases: [setting, option, options]
  view:
    aliases: [viewdistance, distance, vd, renderdistance, render]
    usage: "/view [chunk radius] - Modifies view distance. Radius must be between 3-16. Also note that despite what you set here, you will still need to modify the render distance in Options > Video settings to see further."
  changelog:
    aliases: [log, news, new, updates, whatsnew, changes]
    usage: "/changelog - view the changes and updates made to the server."