name: MountainDewritoes
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.MountainDewritoes.MountainDewritoes
softdepend:
- ExtraHardMode
- Healthbar
- Multiverse-Core
- SimpleClans
- GriefPrevention
- PurpleIRC
- Chester
- EssentialsChat
- HolographicDisplays
- BetterTPA
- MCJukebox
loadbefore:
- AbsorptionShields
commands:
  nick:
    aliases: [color]
  warp: {}
  mdebug: {}
  restart:
    aliases: [stop]
  tip:
    aliases: [getatip, betafish, beta, tips]
  voice:
    aliases: [v]
  shrug: {}