name: MountainDewritoes
version: ${project.version}
#website:
author: RoboMWM
mountainDewritoes: me.robomwm.MountainDewritoes.MountainDewritoes
depend: [SimpleClans]
softdepend: [ExtraHardMode, Healthbar, Multiverse-Core, ActionAPI]