name: MountainDewritoes
version: ${project.version}
#website:
author: RoboMWM
main: me.robomwm.MountainDewritoes.MountainDewritoes
depend: [SimpleClans, ActionAnnouncer]
softdepend: [ExtraHardMode, Healthbar, Multiverse-Core]